NomeFantasia: Warenzeichen
Cnpj: CNPJ
Logradouro: Strasse
Numero: Nummer
Cep: CEP
Bairro: Nachbarschaft
Cidade: Stadt
Estado: Staat
Endereco: Adresse
Telefone: Telefon
Email: E-Mail
Contato: Kontakt
NomeDoResponsavel: Name des verantwortlichen
CpfDoResponsavel: CPF des verantwortlichen
RgDoResponsavel: RG des verantwortlichen
Responsavel: Verantwortlicher
Erro: Fehler bei der Anmeldung

Procedimentos: Prozeduren
NomeFornecedor: Name des Lieferanten
CnpjFornecedor: CNPJ des Lieferanten
TelefoneFornecedor: Telefon des Lieferanten
EmailFornecedor: E-Mail des Lieferanten
Produtos: Produkte
CadastroFornecedor: Lieferanten Registrieren
Preencher: Formular Ausfüllen
MenuLoja: Laden Registrieren
MenuProcedimento: Prozeduren Registrieren
MenuFornecedor: Lieferanten Registrieren
MenuProduto: Produkte Registrieren
MenuSobre: Über

Coleira: Leine
Guia: Führung
Racao: Futter
Remedio: Arzneimittel
Brinquedo: Spielzeuge
Petisco: Snacks
Tratamento: Behandlung
Comida: Schüsseln
Cama: Bette

Banho: Baden
Tosa: Scheren
Unha: Nagelschneiden
Tintura: Färben

CadastroLoja: PetShop Registieren
CadastroProcedimento: Prozeduren Registrieren
CadastroProdutos: Produkt Registrieren
MarqueProdutos: Markiere die Produkte
Mensagem: Schreibe deine Nachricht hier...

Ola: Hallo! Wilkommen zu der Where's Pet Webseite!

Sobre1: Über: 
Sobre2: Diese Webseite wurde von Leonardo Leandro de Sousa, Luisa Negro and Vanessa Pereira Milagres gemacht
Sobre3: als ein Teil des Faches Spezielle Themen in Informatik, gelehrt von Professor Alexandre Garcia de Oliveira
Sobre4: in der FATEC Rubens Lara. Die Webseite ermöglicht das die Tierladen Besitzer sich anmelden, wie auch ihr Laden und die angebotenen Dienstleitungen.

