NomeFantasia: Trade Name
Cnpj: CNPJ
Logradouro: Public Place
Numero: Number
Cep: CEP
Bairro: Neighborhood
Cidade: City
Estado: State
Endereco: Adress
Telefone: Telephone
Email: E-Mail
Contato: Contact
NomeDoResponsavel: Responsible's Name
CpfDoResponsavel: Responsible's CPF
RgDoResponsavel: Responsible's RG
Responsavel: Responsible
Erro: Error in registration

Procedimentos: Procedures
NomeFornecedor: Supplier's Name
CnpjFornecedor: Supplier's CNPJ
TelefoneFornecedor: Supplier's Phone
EmailFornecedor: Supplier's E-mail
Produtos: Products
CadastroFornecedor: Registrate Suppliers
Preencher: Fill the Form
MenuLoja: Shop Registration
MenuProcedimento: Precedure Registration
MenuFornecedor: Supplier Registration
MenuProduto: Product Registration
MenuSobre: About

CadastroLoja: Registrate Pet Shop
CadastroProcedimento: Precedure Registration
CadastroProdutos: Product Registration
MarqueProdutos: Select Products: 
Mensagem: Type your message here...

Coleira: Collars
Guia: Leads
Racao: Foods
Remedio: Medicines
Brinquedo: Toys
Petisco: Treats
Tratamento: Grooming
Comida: Bowls
Cama: Beds

Banho: Bathing
Tosa: Shearing
Unha: Nail cutting
Tintura: Dyeing

Ola: Hello! Welcome to Where's Pet website!

Sobre1: About: 
Sobre2: This website was created by he students Leonardo Leandro de Sousa, Luisa Negro and Vanessa Pereira Milagres
Sobre3:as a part of the discipline Special Topics in Informatics, taught by Professor Alexandre Garcia de Oliveira,
Sobre4: in the System Analysis and Development couse at FATEC Rubens Lara.  The website allows that petshop owners registrate themselves, their store and the services offered by the store.
