NomeFantasia: Nome Fantasia
Cnpj: CNPJ
Logradouro: Logradouro
Numero: Número
Cep: CEP
Bairro: Bairro
Cidade: Cidade
Estado: Estado
Endereco: Endereço
Telefone: Telefone
Email: E-Mail
Contato: Contato
NomeDoResponsavel: Nome do Responsável
CpfDoResponsavel: CPF do Responsável
RgDoResponsavel: RG do Responsável
Responsavel: Responsável
Erro: Erro no cadastro

Procedimentos: Procedimentos
NomeFornecedor: Nome do Fornecedor
CnpjFornecedor: CNPJ do Fornecedor
TelefoneFornecedor: Telefone do Fornecedor
EmailFornecedor: E-mail do Fornecedor
Produtos: Produtos
CadastroFornecedor: Registro de fornecedor
Preencher: Preencha o formulário
MenuLoja: Cadastrar Loja
MenuProcedimento: Cadastrar Procedimento
MenuFornecedor: Cadastrar Fornecedor
MenuProduto: Cadastrar Produto
MenuSobre: Sobre
Coleira: Coleiras
Guia: Guias
Racao: Rações
Remedio: Remédios
Brinquedo: Brinquedos
Petisco: Petiscos
Tratamento: Tratamento
Comida: Comedouros/Bebedouros
Cama: Camas
Banho: Banho
Tosa: Tosa
Unha: Corte de unhas
Tintura: Tintura

CadastroLoja: Cadastrar Pet Shop
CadastroProcedimento: Cadastro de Procedimentos
CadastroProdutos: Cadastro de Produtos
MarqueProdutos: Marque os produtos
Mensagem: Digite sua mensagem aqui...

Ola: Olá! Sejam bem vindos ao site do Where's Pet!

Sobre1: Sobre: 
Sobre2: Este site foi criado pelos alunos Leonardo Leandro de Sousa, Luisa Negro e Vanessa Pereira Milagres
Sobre3: como parte da aula de Tópicos Especiais em Informática, ministrada pelo professor Alexandre Garcia de Oliveira
Sobre4: no curso de Análise e Desenvolvimento de Sistemas na FATEC Rubens Lara. O site permite que donos de pet shop se cadastrem, cadastrem suas lojas e os serviços que a loja oferece.
